INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Pikk 5', 'pv@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD (HOUR, 2, CURRENT_TIMESTAMP), 5, 'Veelaid', 12,' +372 5555 5555');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Pikk 18', 'pva@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD (HOUR, 2, CURRENT_TIMESTAMP), 5, 'Vabarna', 12,' +372 5555 5556');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Pikk 23', 'peeter741@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD (HOUR, 2, CURRENT_TIMESTAMP), 5, 'Lastik', 12,' +372 5555 5557');


